import { LineItem } from './line-item.model';
export interface Order {
    number: string;
    itemTotal?: number;
    total?: number;
    shipTotal?: number;
    state?: string;
    adjustmentTotal?: number;
    userId?: number;
    paymentTotal?: number;
    shipmentState?: string;
    paymentState?: string;
    email?: string;
    specialInstructions?: string;
    includedTaxTotal?: number;
    additionalTaxTotal?: number;
    displayIncludedTaxTotal?: string;
    displayAdditionalTaxTotal?: string;
    taxTotal?: number;
    consideredRisky?: false;
    cancelerId?: number;
    displayItemTotal?: string;
    totalQuantity?: number;
    displayTotal?: string;
    displayShipTotal?: string;
    displayTaxTotal?: string;
    displayAdjustmentTotal?: string;
    token?: string;
    billAddress?: null;
    shipAddress?: null;
    lineItems?: LineItem;
  }
