version: "2"
services:
  angular-cli:
    build:
      context: docker
    ports:
      - "9876:9876"
      - "9000:9000"
    volumes:
      - ./spree-shopping:/workspace
    command: npm start
    environment:
      # ng build --env=stag
      BUILD_ENVIRONMENT: ""